package org.dap.annotators.split_merge;

import org.dap.common.DapAPI;
import org.dap.data_structures.Document;

/**
 * A merger processes a base-document, provided in its constructor, along with additional documents, provided in
 * the {@link #accumulate(Document)} method. The processing ends in the method {@link #conclude()}.
 * 
 * <p>
 * The typical use-case of {@link Merger} is in a split-and-merge flow, implemented in {@link SplitMergeAnnotator}.
 * A {@link Splitter} generates sequence of documents from the base-document. Each of those new documents is annotated by
 * some annotators. Then, the base-document, along with all the documents generated by the {@link Splitter} are provided
 * to the {@link Merger}.
 * 
 * <p>
 * Note that a {@link Merger} can process only one base-document, which is provided in the constructor.
 * Thus, conventionally, a {@link Merger} will be constructed by a {@link MergerFactory}. A {@link MergerFactory} would
 * construct a new {@link Merger} instance for each document.
 * 
 *
 * <p>
 * Date: 31 May 2017
 * @author Asher Stern
 *
 */
@DapAPI
public abstract class Merger
{
	/**
	 * Constructor with the base-document
	 * @param document the base-document
	 */
	@DapAPI
	public Merger(Document document)
	{
		super();
		this.document = document;
	}
	
	/**
	 * This method is called for each additional document (but not for the base-document). The method should be implemented
	 * as some processing (or information-gathering) that uses the given additional-document.
	 * @param document additional-document.
	 */
	@DapAPI
	public abstract void accumulate(Document document);
	
	/**
	 * This method is called <b>after</b> all the additional-documents have been provided to the {@link #accumulate(Document)} method.
	 * This method should be implemented as final processing of the base-document (possibly using the information gathered
	 * during the {@link #accumulate(Document)} invokations).
	 */
	@DapAPI
	public abstract void conclude();

	/**
	 * The base-document.
	 */
	@DapAPI
	protected final Document document;
}
